<a href="https://colab.research.google.com/github/ROBERT-SSEBAMBULIDDE/Machine-Learning-Associate/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Package

In [ ]:
import numpy as np

#an array
a = np.array([1,2,3,4,5]) #1D array
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#a 2D array
b = np.array([[1,2,3],[4,5,6]]) #2D array
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
#accessing elements of an array
a = np.array([1,2,3,4,5])
print(a[0])
print(a[1])

1
2


In [ ]:
#assigning new element to an array
a = np.array([1,2,3,4,5])
a[0] = 10
print(a)

[10  2  3  4  5]


In [ ]:
#slicing an array
a = np.array([1,2,3,4,5])
print(a[0:3]) #first 3 elements

print(a[0:3:2]) #first 3 elements with a step of 2

print(a[:]) #all elements

print(a[::2]) #all elements with a step of 2

print(a[::-1]) #all elements in reverse order

print(a[-1]) #last element

print(a[-2]) #second last element

[1 2 3]
[1 3]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]
5
4


# **ARRAY ATRIBUTES**
 ndim, shape, size, and dtype attributes of an array.

In [ ]:
# ARRAY ATTRIBUTES
#ndim #shape #size #dtype

#ndim
a = np.array([1,2,3,4,5])
print(a.ndim) #show dimension of the array

#shape
a = np.array([1,2,3,4,5])
print(a.shape) #show shape of the array

#size
a = np.array([1,2,3,4,5])
print(a.size) #show size of the array

#dtype
a = np.array([1,2,3,4,5])
print(a.dtype) #show data type of the array

1
(5,)
5
int64


# **How to create a basic array**
 np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [ ]:
#np.zeros()
a = np.zeros((3,4)) #3 rows and 4 columns
print(a)

#np.ones()
a = np.ones((3,4)) #3 rows and 4 columns
print(a)

#np.arange()
a = np.arange(10) #1D array with 10 elements
print(a)

a = np.arange(10,20) #1D array with 10 elements between 10 and 20
print(a)

a = np.arange(10,20,2) #1D array with 10 elements between 10 and 20 with a step of 2
print(a)
#np.linspace()
a = np.linspace(0,1,5) #1D array with 5 elements between 0 and 1
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#specifying data type
a = np.array([1,2,3,4,5], dtype=np.float64) #1D array with 5 elements of float64 data type
print(a)

a = np.array([1,2,3,4,5], dtype=np.int32) #1D array with 5 elements of int32 data type
print(a)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


# **Adding, removing, and sorting elements**
np.sort(), np.concatenate()

In [ ]:
#np.sort()
a = np.array([5,2,1,3,4,5])
np.sort(a) #sort the array in ascending order
print(a)

[5 2 1 3 4 5]


In [ ]:
#concatenate
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.concatenate((a,b)) #concatenate two arrays
print(a)
print(b)
c=np.concatenate((a,b), axis=0) #concatenate two arrays along the first axis
print(a)
print(b)
print(c)

[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#concatenate 2 dimension arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
np.concatenate((a,b)) #concatenate two arrays
print(a)
print(b)
c=np.concatenate((a,b), axis=1) #concatenate two arrays along the second axis
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#remove elements
a = np.array([1,2,3,4,5])
b=np.delete(a,2) #remove the third element
print(b)

[1 2 4 5]


In [ ]:
#removing elements by slicing
a = np.array([1,2,3,4,5])
b=a[:2] #remove the first two elements
print(b)

[1 2]


In [ ]:
c=a[2:4] #remove the last two elements
print(c)

[3 4]


# **Reshape an array**
arr.reshape()

In [ ]:
a=np.arange(1,10) #1D array with 9 elements
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
b=a.reshape(3,3) #reshape the array to 3 rows and 3 columns
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **How to convert a 1D array into a 2D array (how to add a new axis to an array)**
 np.newaxis, np.expand_dims

In [ ]:
#converting 1D array to 2D array by adding a new axis
a = np.array([1,2,3,4,5])
b = a[:, np.newaxis] #add a new axis to the array as a column Vector
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
b.shape

(5, 1)

In [ ]:
b.ndim

2

In [ ]:
#converting 1D array to 2D array by adding a new axis
a = np.array([1,2,3,4,5])
b = a[np.newaxis, :] #add a new axis to the array as a row Vector
print(b)

[[1 2 3 4 5]]


In [ ]:
#check shape
b.shape

(1, 5)

In [ ]:
b.ndim

2

In [ ]:
#Expand axis
a=np.arange(5,20)
print(a)
b=np.expand_dims(a, axis=1) #add a new axis to the array as a column Vector
print(b)
b.shape

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


(15, 1)

In [ ]:
b.ndim

2

In [ ]:
#adding an axis at specified position
a=np.arange(5,20)
print(a)
b=np.expand_dims(a, axis=0) #add a new axis to the array as a row Vector
print(b)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [ ]:
b.shape

(1, 15)

In [ ]:
b.ndim

2

# **Indexing and slicing**

In [ ]:
data=np.array([[1,2,3,4,5],[6,7,8,9,10],[23,24,25,26,27]])
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [23 24 25 26 27]]


In [ ]:
data[2,4] #access the element in the third row and fifth column

27

In [ ]:
data[:,4] #access the fifth column

array([ 5, 10, 27])

In [ ]:
data[1,:] #access the second row

array([ 6,  7,  8,  9, 10])

In [ ]:
#conditional selection
data[data>5] #select all elements greater than 5

array([ 6,  7,  8,  9, 10, 23, 24, 25, 26, 27])

In [ ]:
data[data<5] #select all elements less than 5


array([1, 2, 3, 4])

In [ ]:
data[data==5] #select all elements equal to 5


array([5])

In [ ]:
data[data!=5] #select all elements not equal to 5

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 23, 24, 25, 26, 27])

In [ ]:
data[data%2==0] #select all elements that are even

array([ 2,  4,  6,  8, 10, 24, 26])

In [ ]:
data[data%2!=0] #select all elements that are odd

array([ 1,  3,  5,  7,  9, 23, 25, 27])

In [ ]:
#logical operators
data[(data>5) & (data<10)] #select all elements greater than 5 and less than 10

array([6, 7, 8, 9])

# **How to create an array from existing data**
 slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
#slicing to create a new array
a[0:3] #first 3 elements

array([1, 2, 3])

In [ ]:
a[0:3:2] #first 3 elements with a step of 2

array([1, 3])

In [ ]:
a[:] #all elements

array([1, 2, 3, 4, 5])

In [ ]:
a[::-1] #all elements in reverse order



array([5, 4, 3, 2, 1])

In [ ]:
a[-1] #last element

5

In [ ]:
a[-2] #second last element

4

In [ ]:
#indexing to create new array
a[0:3] #first 3 elements

array([1, 2, 3])

In [ ]:
#np.vstack()
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=np.vstack((a,b)) #stack two arrays vertically
print(c)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#np.hstack()
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=np.hstack((a,b)) #stack two arrays horizontally
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#hssplit()
a=np.arange(1,25).reshape(2,12)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [ ]:
#splitting into two arrays
b=np.hsplit(a,3) #split the array into two arrays
print(a)
b

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
#view
a = np.array([1,2,3,4,5])
b=a.view() #create a view of the array and assign it to b but does not change the original array
print(a)
print(b)
b[0]=10 #change the first element of the view also changes the original array because it is a view
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]
[10  2  3  4  5]


In [ ]:
#copy
a = np.array([1,2,3,4,5])
b=a.copy() #create a copy of the array and assign it to b but does not change the original array
print(a)
print(b)
b[0]=10 #change the first element of the copy also changes the original array because it is a copy
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]


# **Basic array operations**
covers addition, subtraction, multiplication, division, and more

In [ ]:
#addition
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=a+b #add two arrays
print(c)

#addition of 2D arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c=a+b #add two arrays by adding the corresponding elements
print(c)

[ 7  9 11 13 15]
[[ 8 10 12]
 [14 16 18]]


In [ ]:
#using the sum
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=np.sum([a,b]) #add two arrays by adding the corresponding elements
print(c)

55


In [ ]:
#Subtraction
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=a-b #subtract two arrays
print(c)

#Subtraction of 2D arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c=a-b #subtract two arrays by subtracting the corresponding elements
print(c)

[-5 -5 -5 -5 -5]
[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
#multiplication
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=a*b #multiply two arrays
print(c)

#multiplication of 2D arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c=a*b #multiply two arrays by multiplying the corresponding elements
print(c)

#division
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=a/b #divide two arrays
print(c)

[ 6 14 24 36 50]
[[ 7 16 27]
 [40 55 72]]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
#division of 2D arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c=a/b #divide two arrays by dividing the corresponding elements
print(c)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# **Broadcasting**
There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes.

In [ ]:
#What is broadcasting?
#Broadcasting is a way to make two arrays of different shapes work together by automatically expanding one of the arrays to match the shape of the other array.
a = np.array([1,2,3,4,5])
b = 2 #scalar
c=a*b #multiply two arrays
print(c)

[ 2  4  6  8 10]


In [ ]:
#Broadcasting of 2D arrays
a = np.array([[1,2,3],[4,5,6]])
b = 2 #scalar
c=a*b #multiply two arrays by multiplying the corresponding elements
print(c)

[[ 2  4  6]
 [ 8 10 12]]


# **Other array operations**
maximum, minimum, sum, mean, product, standard deviation, and more

NumPy also performs aggregation functions. In addition to min, max, and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

In [ ]:
a=np.array([1,2,3,4,5])
b=np.max(a) #get the maximum value in the array
print(b)

5


In [ ]:
#min
b=np.min(a) #get the minimum value in the array
print(b)


1


In [ ]:
#mean
b=np.mean(a) #get the mean value in the array
print(b)



3.0


In [ ]:

#sum
b=np.sum(a) #get the sum of the array
print(b)

15


In [ ]:
#median
b=np.median(a) #get the median value in the array
print(b)

3.0


In [ ]:
#standard deviation
b=np.std(a) #get the standard deviation of the array
print(b)

1.4142135623730951


In [ ]:
#variance
b=np.var(a) #get the variance of the array
print(b)

2.0


In [ ]:
#dot
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c=np.dot(a,b) #multiply two arrays and sum then elements
print(c)

130


# **Creating matrices**

In [ ]:
# create a matrix
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


# **Generating random numbers**

In [ ]:
#generating random numbers
a = np.random.rand(2,3) #generate random numbers between 0 and 1
print(a)

[[0.25140479 0.86683356 0.88936873]
 [0.37173486 0.62312948 0.5461555 ]]


In [ ]:
#generating random integers
a = np.random.randint(0,10,(2,3)) #generate random integers between 0 and 10
print(a)

[[6 0 2]
 [1 4 7]]


# **How to get unique items and counts**

In [ ]:
#unique values and counts
a = np.array([1,2,3,4,5,5,6,7,7,8,9,10])
b=np.unique(a) #get the unique values in the array
print(b)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
c=np.unique(a,return_counts=True) #get the unique values in the array and their counts
print(c)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([1, 1, 1, 1, 2, 1, 2, 1, 1, 1]))


In [ ]:
#2D arrays
a = np.array([[1,2,3],[4,5,6]])
b=np.unique(a) #get the unique values in the array
print(b)
c=np.unique(a,return_counts=True) #get the unique values in the array and their counts
print(c)

[1 2 3 4 5 6]
(array([1, 2, 3, 4, 5, 6]), array([1, 1, 1, 1, 1, 1]))


# **Transposing and reshaping a matrix**
arr.reshape(), arr.transpose(), arr.T

In [ ]:
#reshape
a = np.array([1,2,3,4,5,6])
b=a.reshape(2,3) #reshape the array into a 2x3 matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#transpose
a = np.array([[1,2,3],[4,5,6]])
b=a.T #transpose the array
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# **How to reverse an array**
covers np.flip()

In [ ]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#flip
a=np.flip(a) #flip the array.This reverses the order of the elements in the array
print(a)

[9 8 7 6 5 4 3 2 1]


In [ ]:
#2d arrays
a=np.arange(1,10).reshape(3,3)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#flip
a=np.flip(a) #flip the array.This reverses the order of the elements in the array
print(a)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:

#flip
a=np.flip(a,0) #flip the array along the first axis.This reverses the order of the elements in the first dimension of the array
print(a)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


# **Reshaping and flattening multidimensional arrays**
 covers .flatten(), ravel()

There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

In [ ]:
#flattening
a=np.arange(1,10).reshape(3,3)
print(a)
b=a.flatten() #flatten the array into a 1D array
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
b[0]=10 #change the first element of the flattened array
print(b)

[10  2  3  4  5  6  7  8  9]


In [ ]:
#check if a has changed after changing the first element of the flattened array
print(a) #the original array has not changed

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#ravel
a=np.arange(1,10).reshape(3,3)
print(a)
b=a.ravel() #flatten the array into a 1D array
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
b[0]=10  #change the first element of the flattened array
print(a) #the original array has changed
print(b)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[10  2  3  4  5  6  7  8  9]


# **Working with mathematical formulas**